kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gadget-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: gadget
  namespace: gadget
roleRef:
  kind: ClusterRole
  name: gadget-cluster-role
  apiGroup: rbac.authorization.k8s.io