apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gadget
  name: gadget-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  # update is needed by traceloop gadget.
  verbs: ["update"]