apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gadget-role-binding
  namespace: gadget
subjects:
- kind: ServiceAccount
  name: gadget
roleRef:
  kind: Role
  name: gadget-role
  apiGroup: rbac.authorization.k8s.io